### ISSUE TITLE
能不能一起开发？

### ISSUE THREAD

**Issue by Jdoing** [knightliao/CanalX#5]

**Comment by gangh** [comment]
赞,最近也有类似的需求
@Jdoing  [这个项目](https://github.com/liukelin/canal_mysql_nosql_sync)中也是做了类型的工作,但(url) sql -> json 的格式有较大差异,你采用了什么样的方案呢

**Comment by Jdoing** [comment]
直接转成另外领域的对象

**Comment by knightliao** [comment]
最近会重启这个项目，请关注
